### ISSUE TITLE
Could not execute query - unable to open database file: out of memory (14)

### ISSUE THREAD

**Issue by pseudozach** [fr-ser/grafana-sqlite-datasource#103]
**Describe the bug**
I'm able to successfully import a 2MB+ sqlite3 db file into grafana. But when I try to run a basic query, I get this error:
>logger=plugin.frser-sqlite-datasource t=2022-11-16T06:34:44.612548514Z level=error msg="Could not execute query" err="unable to open database file: out of memory (14)" query="select * from apipayments;"

**To Reproduce**

1. run grafana with docker, bind a local file to the docker with -v
2. install this plugin
3. setup a panel using the sqlite3 file

**Screenshots**
![Screen Shot 2022-11-15 at 10 47 21 PM](https://user-images.githubusercontent.com/3731591/202105342-880cc129-35f5-4928-b57e-77cdf290cd47.png)

**Versions (please complete the following information):**

- OS: debian 10
- Run via docker? yes
- Browser chrome
- Grafana Version 9.3.0-beta1
- Plugin Version 3.1.0
- Plugin installed via grafana-cli or manually? from GUI

**Additional context**
VM has 64GB RAM so there's plenty of memory available.

**Comment by fr-ser** [comment]
Interesting behavior indeed. Do you see the same for older versions of Grafana?
And do you have a full debug level log to check?
