### ISSUE TITLE
Can not convert to wide series, expected long format series input but got not series

### ISSUE THREAD

**Issue by mammuthus** [fr-ser/grafana-sqlite-datasource#105]
**Describe the bug**
Getting an error: "can not convert to wide series, expected long format series input but got not series", while settings seems to be valid. No error description was found.

Dataset:

```
timestamp|message
2023-02-23 09:26:59|115
2023-01-28 10:22:07|113
2023-01-05 23:38:38|113.5
2022-11-11 09:33:43|112
2022-10-05 11:03:23|112.3
2022-09-17 10:27:43|112.6
```

Query:

```
SELECT
timestamp,
message as value

FROM messages
ORDER BY timestamp
```

**To Reproduce**

1. Make a new time-series widget using my query with my dataset
2. Receive an error

**Screenshots**
![image](https://user-images.githubusercontent.com/1700286/221378190-19a01ccc-c657-444f-ac26-aea7f5c3da37.png)
![image](https://user-images.githubusercontent.com/1700286/221023076-aa53c5c5-cc09-4414-b754-4f0ea43d0da7.png)

**Versions (please complete the following information):**

- OS: Fedora 37
- Run via docker? - Yes
- Browser - Chrome
- Grafana Version - v9.3.6 (978237e7cb)
- Plugin Version - 3.1.0
- Plugin installed via grafana-cli or manually? - From Grafana web interface

**Comment by fr-ser** [comment]
"2023-02-23 09:26:59" seems like a not particularly ISO compliant string format.

Can you try to make sure that the timestamp is actually recognized as such correctly?

For example. Could you run the same query against unix timestamps (integer numbers) and see what you get?

**Comment by mammuthus** [comment]
You mean like
![image](https://user-images.githubusercontent.com/1700286/221374119-3aea272b-f0db-40d4-95ae-2867046a4f29.png)
?

**Comment by fr-ser** [comment]
I am not sure if having multiple values for a single timestamp is a problem.

I will take a look in a bit. 👌

**Comment by mammuthus** [comment]
By the way, I converted the timestamp to Unix Epoch, so it should be native for the plugin now, and the result is the same

New dataset:
![image](https://user-images.githubusercontent.com/1700286/221378048-c48102fa-287b-4507-9956-ed88d88dd4f0.png)

Result:
![image](https://user-images.githubusercontent.com/1700286/221378110-3a15270a-47af-4a29-9986-201df2722076.png)

**Comment by mammuthus** [comment]
@fr-ser LMAO, I'm dumb. message was a _string_, so obviously it won't work until I convert it to numeric. 
```
SELECT timestamp as time, CAST(message AS INTEGER) as value
FROM messages 
ORDER BY timestamp ASC
```
Thank you for your time.

**Comment by fr-ser** [comment]
Let me reopen the issue so I will remember to take a look later if the error message can be improved

**Comment by DhanushDK17** [comment]
What should be the timestamp's datatype in the table schema? I'm trying to visualize something similar but the data in the timestamp column disappears as soon as I add that column as a time formatted column.
<img width="1023" alt="image" src="https://github.com/fr-ser/grafana-sqlite-datasource/assets/22236367/f0db00ed-ecae-4dee-9b2a-d55eafa116d8">

**Comment by fr-ser** [comment]
@DhanushDK17 you can have a look at this section: https://github.com/fr-ser/grafana-sqlite-datasource#support-for-time-formatted-columns

If that does not answer the question please open a new issue and we can have a look

**Comment by fr-ser** [comment]
It is tricky to improve the error message without analyzing the data frame in depth. Currently, I make use of the standard Grafana method to check the validity of the series. 

Unless there are more problems with similar issues in the future I'll leave it at that.
