### ISSUE TITLE
"Plugin Unavailable": File permissions

### ISSUE THREAD

**Issue by farmboy-dev** [fr-ser/grafana-sqlite-datasource#107]
In my case, I solved the error changing permission for files in the plugin folder.
Like this: chmod 755 gpx_sqlite-datasource_linux. ~~ 
If you are using docker, access the container using root mode ( -itu 0 container_name)

**Comment by fr-ser** [comment]
> If you are using docker, access the container using root mode ( -itu 0 container_name)

That will likely be lost again when the docker container restarts, though.

> In my case, I solved the error changing permission for files in the plugin folder.

What permissions did you have before? How did you download/install the plugin?
