### ISSUE TITLE
High memory usage (possible memory leak)

### ISSUE THREAD

**Issue by k-bx** [fr-ser/grafana-sqlite-datasource#110]
**Describe the bug**
Memory usage is quickly growing for the plugin. It's now 865M and was previously multiple gigabytes (before the restart). Whenever I update the dashboard page RAM usage gets up by ~15 Mb. I've made several refreshes and it's now over 1G.

**To Reproduce**
Configure a dashboard with SQLite source. Refresh several times (via "refresh" button in grafana is ok).

**Screenshots**
<img width="1448" alt="зображення" src="https://github.com/fr-ser/grafana-sqlite-datasource/assets/107968/10ee815b-682c-4f0d-b519-d0b20f0ee8bb">

<img width="1054" alt="зображення" src="https://github.com/fr-ser/grafana-sqlite-datasource/assets/107968/23da504a-92c5-4f62-a9b0-0c5dd40e53e9">

**Versions (please complete the following information):**

- OS: Ubuntu 22.04
- Run via docker? No
- Grafana Version 10.0.1
- Plugin Version 3.3.0
- Plugin installed via grafana-cli or manually? grafana-cli

**Comment by fr-ser** [comment]
Could you please also provide an example dataset and query so I can reproduce the issue?

**Comment by kosmgco** [comment]
Maybe need to close the `conn` in query.go:250?

When running a period of time, use `lsof` command, we can see many opened database file in this process

**Comment by fr-ser** [comment]
Can you try out if this version fixes the issue: https://github.com/fr-ser/grafana-sqlite-datasource/releases/tag/v3.3.1

**Comment by k-bx** [comment]
Looks much better now, thank you! @fr-ser Sits on ~30Mb RAM. Will keep an eye on it for a longer period, otherwise marking as fixed.
