### ISSUE TITLE
$__interval_ms compatible macro

### ISSUE THREAD

**Issue by TuomasKiviaho** [fr-ser/grafana-sqlite-datasource#117]
Currently there is no macro suitable for handling interval `cast(time / ($__interval_ms / 1000) as int) * ($__interval_ms / 1000)` since division can't be done in the macro parameter (that I'm aware of)

https://github.com/fr-ser/grafana-sqlite-datasource/blob/e35eef3e527f4ef810e952cabd8592d8522124f2/pkg/plugin/macros.go#L51

I believe there is something a kin in the postgre  data source

**Comment by fr-ser** [comment]
I am not sure I fully understand the scenario. Could you provide a sample query with some data in a CTE or subquery and explain based on that what you are trying to see and what is missing?
