### ISSUE TITLE
Variables: Query returns no results

### ISSUE THREAD

**Issue by sensej-j** [fr-ser/grafana-sqlite-datasource#118]
Hi Sergej,
this Variable-Query returns no results.

SELECT Raum FROM tws_config_new where [Typ] = 1 OR SELECT Raum FROM tws_config_new where Typ = 1
Everything runs successfully in DB Browser.
When I click "run query" nothing happens.

![image](https://github.com/fr-ser/grafana-sqlite-datasource/assets/78264478/0812737b-f8ff-48d3-bc48-db45eaadc31c)

What could that be? 

That is how it goes, without "WHERE"
SELECT Raum FROM tws_config_new;

- OS: Debian Stretch (9.13)
- Run via docker: yes
- Browser: chrome
- Grafana Version: 10.0.3
- Grafana Container: grafana:10.0.3-ubuntu
- SQLite Plugin Version: 3.3.2

**Comment by fr-ser** [comment]
Can you provide a test dataset?

**Comment by sensej-j** [comment]
Hello Sergei,
I checked everything again yesterday. 
Sorry, that was my mistake.
Everything works.
