### ISSUE TITLE
Support for annotations

### ISSUE THREAD

**Issue by GregCornis** [fr-ser/grafana-sqlite-datasource#119]
Just wondering if the plugin supports Grafana annotations ? I do not see the "SQLite" listed in the available data sources when creating a query annotation, from the dashboard.

**Comment by fr-ser** [comment]
I must say I just never really used annotations. I'll have to see what those are and what is required to get those working.

I'll take a look and post updates here.

**Comment by eeddaann** [comment]
Hey,
I have followed the steps on [Grafana's docs](https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/enable-for-annotations) and implemented them [here](https://github.com/fr-ser/grafana-sqlite-datasource/pull/122) . The default behavior looks fine - tested manually.

**Comment by fr-ser** [comment]
Thanks a lot to @eeddaann for the annotations feature!

I created a new release with those changes https://github.com/fr-ser/grafana-sqlite-datasource/releases/tag/v3.4.0

Please have a look and see if this works as expected. I would release the new version to the official Grafana repository if I don't hear about any bugs in the following weeks

**Comment by GregCornis** [comment]
I didn't manage to test this, as 3.4.0 is not yet on Grafana Plugin Registry. I did follow the [manual installation procedure](https://github.com/fr-ser/grafana-sqlite-datasource/blob/main/docs/installation.md) but couldn't get it to work it seems. Everytime I restarted the service (i'm on MacOS), the plugin 3.3.2 reappeared. Do you know how I can test ? Actually do you even _need_ me to test ?

**Comment by fr-ser** [comment]
This command should do the trick:

> grafana-cli --pluginUrl https://github.com/fr-ser/grafana-sqlite-datasource/releases/download/v3.4.0/frser-sqlite-datasource-3.4.0.zip plugins install frser-sqlite-datasource

If this does not work I don't know without further information what the issue might be.

While it would be nice to have someone check that the issue is resolved it is not necessary. I started the release process of the plugin now and in the near future it should be available via the Grafana plugin registry as well.
