### ISSUE TITLE
Support for `__text` and `__value` in variables

### ISSUE THREAD

**Issue by gelicia** [fr-ser/grafana-sqlite-datasource#120]
**Describe the bug**
In Grafana, users can set up query variables to build variable lists for filtering their dashboards. To support a key/value structure to these lists, there is the option of using `__text` and `__value` ([ref](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-a-query-variable)) as aliases so one value will be displayed and one will be used as the filter.

This datasource automatically throws an error whenever more than one field is returned when building this list ([src](https://github.com/fr-ser/grafana-sqlite-datasource/blob/main/src/DataSource.ts#L43)) which prevents this functionality from working.

**To Reproduce**

1. Be sure this datasource is installed in Grafana. I use a SQLite database for Grafana itself, so I set up the datasource to reference that database.
2. In a dashboard, click the gear to access settings, then go to Variables
3. Create a query variable with the name and label of users. "Show on dashboard" has "Label and value" selected. 
4. Select your SQLite datasource, and under query, add `SELECT id AS __value, login AS __text FROM user`
5. Use defaults for everything else
6. Either apply the variable or click "Run query" 
7. See the error about two fields 

**Versions (please complete the following information):**

- OS: OSX
- Run via docker? No
- Browser: Chrome
- Grafana Version: main
- Plugin Version: 3.3.2
- Plugin installed via grafana-cli or manually? Installed via UI

**Comment by fr-ser** [comment]
Thank you very much for the detailed report. I'll take a look at this 👌🏻

**Comment by fr-ser** [comment]
The support for this should be added via this PR: https://github.com/fr-ser/grafana-sqlite-datasource/pull/133.

You can manually install [v3.5.0 of the plugin right now to check it](https://github.com/fr-ser/grafana-sqlite-datasource/releases/tag/v3.5.0).

After a while (a couple of weeks usually) the plugin is also updated on the regular Grafana release channels
