### ISSUE TITLE
sqlite3 plugins don't visible in grafana web page

### ISSUE THREAD

**Issue by alvarotir** [fr-ser/grafana-sqlite-datasource#121]
**Describe the bug**
hi, I manually installed the latest version of your sqlite3 plugins in the path /var/lib/grafana/plugins, restarted the grafana service but unfortunately this is not visible in the web section from the datasources

**To Reproduce**

[root@SPE1mpxytool12 frser-sqlite-datasource]# pwd
/var/lib/grafana/plugins/frser-sqlite-datasource

[root@SPE1mpxytool12 frser-sqlite-datasource]# ll
total 147412
-rw-r--r-- 1 grafana grafana     8330 Dec 11 16:17 CHANGELOG.md
-rwxr-xr-x 1 grafana grafana     1440 Dec 11 16:17 go_plugin_build_manifest
-rwxr-xr-x 1 grafana grafana 22039872 Dec 11 16:17 gpx_sqlite-datasource_darwin_amd64
-rwxr-xr-x 1 grafana grafana 21772546 Dec 11 16:17 gpx_sqlite-datasource_darwin_arm64
-rwxr-xr-x 1 grafana grafana 28870072 Dec 11 16:17 gpx_sqlite-datasource_freebsd_amd64
-rwxr-xr-x 1 grafana grafana 19812352 Dec 11 16:17 gpx_sqlite-datasource_linux_amd64
-rwxr-xr-x 1 grafana grafana 18939904 Dec 11 16:17 gpx_sqlite-datasource_linux_arm
-rwxr-xr-x 1 grafana grafana 19136512 Dec 11 16:17 gpx_sqlite-datasource_linux_arm64
-rwxr-xr-x 1 grafana grafana 20233728 Dec 11 16:17 gpx_sqlite-datasource_windows_amd64.exe
drwxr-xr-x 2 grafana grafana      104 Dec 11 16:17 img
-rw-r--r-- 1 grafana grafana    11357 Dec 11 16:17 LICENSE
-rw-r--r-- 1 grafana grafana     2429 Dec 11 16:17 MANIFEST.txt
-rw-r--r-- 1 grafana grafana    17400 Dec 11 16:17 module.js
-rw-r--r-- 1 grafana grafana    71646 Dec 11 16:17 module.js.map
-rw-r--r-- 1 grafana grafana     1152 Dec 11 16:17 plugin.json
-rw-r--r-- 1 grafana grafana     7242 Dec 11 16:17 README.md

[root@SPE1mpxytool12 frser-sqlite-datasource]# systemctl status grafana-server
* grafana-server.service - Grafana instance
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; disabled; vendor preset: disabled)
   Active: activating (start) since Thu 2023-12-14 10:44:25 CET; 2s ago
     Docs: http://docs.grafana.org
 Main PID: 499998 (grafana)
    Tasks: 11 (limit: 24858)
   Memory: 89.8M
   CGroup: /system.slice/grafana-server.service
           |-499998 /usr/share/grafana/bin/grafana server --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid --packaging=rpm cfg:default.paths.logs=/var/log/grafana cfg:default>
           `-500003 /var/lib/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_linux_amd64

Dec 14 10:44:25 SPE1mpxytool12 grafana[499998]: logger=settings t=2023-12-14T10:44:25.490148234+01:00 level=info msg="App mode production"
Dec 14 10:44:25 SPE1mpxytool12 grafana[499998]: logger=sqlstore t=2023-12-14T10:44:25.49021832+01:00 level=info msg="Connecting to DB" dbtype=sqlite3
Dec 14 10:44:25 SPE1mpxytool12 grafana[499998]: logger=migrator t=2023-12-14T10:44:25.490865449+01:00 level=info msg="Starting DB migrations"
Dec 14 10:44:25 SPE1mpxytool12 grafana[499998]: logger=migrator t=2023-12-14T10:44:25.509201742+01:00 level=info msg="migrations completed" performed=0 skipped=608 duration=633.121µs
Dec 14 10:44:25 SPE1mpxytool12 grafana[499998]: logger=licensing t=2023-12-14T10:44:25.510057186+01:00 level=info msg="Validated license token" appURL=http://localhost:3000/ source=disk status=NotFound
Dec 14 10:44:25 SPE1mpxytool12 grafana[499998]: logger=secrets t=2023-12-14T10:44:25.510447289+01:00 level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
Dec 14 10:44:25 SPE1mpxytool12 grafana[499998]: logger=plugins.registration t=2023-12-14T10:44:25.577761562+01:00 level=info msg="Plugin registered" pluginId=input
Dec 14 10:44:26 SPE1mpxytool12 grafana[499998]: logger=plugins.registration t=2023-12-14T10:44:26.202194626+01:00 level=info msg="Plugin registered" pluginId=frser-sqlite-datasource
Dec 14 10:44:26 SPE1mpxytool12 grafana[499998]: logger=query_data t=2023-12-14T10:44:26.223692133+01:00 level=info msg="Query Service initialization"
Dec 14 10:44:26 SPE1mpxytool12 grafana[499998]: logger=live.push_http t=2023-12-14T10:44:26.227944054+01:00 level=info msg="Live Push Gateway initialization

**Screenshots**
![image](https://github.com/fr-ser/grafana-sqlite-datasource/assets/153816281/1b584a8a-39d5-4f61-bd6f-202dd9fc3df3)

**Versions (please complete the following information):**

- OS: Red Hat 8.8
- Run via docker? no
- Browser chrome,
- Grafana Version enterprise 10.2.2
- Plugin Version 3.3.3
- Plugin installed via grafana-cli or manually? manually

**Additional context**
I don't have internet connection

**Comment by fr-ser** [comment]
Could you provide the full log message from Grafana after startup at debug level?

More information here: https://grafana.com/docs/grafana/latest/troubleshooting/#troubleshoot-with-logs
