### ISSUE TITLE
:permission denied

### ISSUE THREAD

**Issue by Frederic-SABU** [fr-ser/grafana-sqlite-datasource#127]
**Describe the bug**
Unable to open an sqlite3 base in Grafana (local not cloud)

**To Reproduce**
Add the sqlite plugin to Grafana
Try to open a local sqlite3 database
Grafana unable to access the data
I have tried the FAQ patches by toggling the Protect_Home from true to false with no avail.
The DB opens correctly with Python and DB Browser

**Screenshots**
![image](https://github.com/fr-ser/grafana-sqlite-datasource/assets/50482551/aac47870-f77d-4d13-b4b4-295f37d5c63c)

**Versions (please complete the following information):**

- OS: Ubuntu 22
- Run via apt package
- Browser chrome
- Grafana Version 10.2.3
- Plugin Version 3.4.0
- Plugin installed via grafana-cli 

**Additional context**
Add any other context about the problem here. Please also attach the logs of Grafana!

**Comment by fr-ser** [comment]
What about the permissions?

Can the Grafana user access every part of the path?

**Comment by Frederic-SABU** [comment]
I have indeed already seen that comment but not sure about what is a Grafana User. I have set the database file permission to R&W. I can obviously access them but again from Grafana side I am a bit puzzled ?

**Comment by fr-ser** [comment]
Normally Grafana has a custom user (named Grafana) that it creates during the installation.

You need to make sure that this user can read the database.

And you also need to make sure that this user can read all directories in the path of the file.

**Comment by Frederic-SABU** [comment]
Actually the default user was admin and it got the administration right. I have even tried to create an extra user with admin righhts as well. Same problem. I think I will stop at my Grafana atempt at this stage it is far too time consuming. I will go back to MathPlot scripts. Thks for helping out anyway.

**Comment by Frederic-SABU** [comment]
Thks.
