### ISSUE TITLE
Permission denied on Grafana Cloud

### ISSUE THREAD

**Issue by edervishaj** [fr-ser/grafana-sqlite-datasource#128]
I am using the free tier of Grafana Cloud. I want to setup a SQLite database as a data source but after I installed the plugin (via the Grafana cloud plugins page) and set the absolute path to the `.sqlite` file, I got a permission denied error. The database is under `/root` and I tried overriding `systemd` with `ProtectHome=false` as suggested in the documentation. I changed the group of the entire path of the database to `grafana-agent` group which includes the `grafana-agent` user.

Any ideas on what to try next?

**Comment by fr-ser** [comment]
This sentence makes me a bit skeptical already: "I am using the free tier of Grafana Cloud".

Grafana Cloud runs in the cloud. SQLite is a local database. The only SQLite file for Grafana Cloud would be the internal database, no?

Can you confirm that you are indeed hosting Grafana and the SQLite database on the same system?

**Comment by edervishaj** [comment]
Grafana cloud runs in the cloud but it involves installing Grafana agent (https://grafana.com/docs/agent/latest) locally on the server (where the SQLite database is).

**Comment by fr-ser** [comment]
After reading this page (<https://grafana.com/docs/grafana-cloud/send-data/agent/>) it looks like the "Grafana agent" is simply a logs and metrics collector. It does not run data source plugins.

As far as I am aware there is no way to run Grafana cloud and still use local data source plugins (like SQLite, CSV, ...).

If you hear or read anything else please let me know.
