### ISSUE TITLE
Manual Installation failed with newest release

### ISSUE THREAD

**Issue by sebastianmaul** [fr-ser/grafana-sqlite-datasource#129]
I wanted to install the version 3.4.0 of the plugin manually because the IPC that I use, has no access to the internet. And it did not show in the plugins / datasources even though I did every step.
With the version 3.3.3 I tried again and did the same steps as before and it worked and showed in Grafana

- Grafana Version [10.0.0]
- Plugin Version [3.4.0]

**Comment by fr-ser** [comment]
Grafana v10 is something I have not tried yet.

Would you happen to have the debug level startup logs available for the installation of v3.4.0?

**Comment by sebastianmaul** [comment]
[grafana_log.txt](https://github.com/fr-ser/grafana-sqlite-datasource/files/14416056/grafana_log.txt)

I hope that this helps, because I had to test on another system not on the IPC I was talking about. I will double check on the IPC within this week.

**Comment by fr-ser** [comment]
From the logs everything looks good. But I see this

> logger=plugin.frser-sqlite-datasource t=2024-02-27T08:37:23.3824104+01:00 level=debug msg="plugin started" path="C:\\Program Files\\GrafanaLabs\\grafana\\data\\plugins\\frser-sqlite-datasource_3.3.3/gpx_sqlite-datasource_windows_amd64.exe" pid=16840

So it is version 3.3.3. Are those the logs from an installation of v3.4.0 that did not start?
