### ISSUE TITLE
Unable to install 4040 not found error

### ISSUE THREAD

**Issue by EdDred** [fr-ser/grafana-sqlite-datasource#13]
pi@raspberrypi:/etc/grafana $ grafana-cli plugins install frser-sqlite-datasource
Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error

**Comment by fr-ser** [comment]
The plugin is not released yet as an official grafana plugin. Please use the manual installation method instead: https://github.com/fr-ser/grafana-sqlite-datasource#installing-the-plugin-manually-on-an-existing-grafana

**Comment by EdDred** [comment]
the instruction is not correct then as a first option

**Comment by fr-ser** [comment]
It should be the first option, but only after grafana approves the plugin. Which seems to take forever...

But thank you for pointing out the inconsistency in the README. I updated it already :ok_hand:
