### ISSUE TITLE
frser-sqlite-datasource v3.5.0 either does not exist or is not supported on your system linux-amd64

### ISSUE THREAD

**Issue by sensej-j** [fr-ser/grafana-sqlite-datasource#136]
Hello Sergei,
when installing frser-sqlite-datasource v3.5 I get this error message.

Error: frser-sqlite-datasource v3.5.0 either does not exist or is not supported on your system linux-amd64

What am I doing wrong?

frser-sqlite-datasource Version: 3.5.0
- Run via docker: yes
- Browser: chrome
- Grafana Version: 10.4.0
- Plugin Version: 3.5.0
- Plugin installed via grafana-cli or manually: grafana-cli

Kind regards sensej

**Comment by fr-ser** [comment]
Can you provide the exact command you are using?

Can you also check if the same thing happens for v3.4.0?

**Comment by sensej-j** [comment]
Command: grafana-cli plugins install frser-sqlite-datasource 3.5.0

this command works (grafana-cli plugins install frser-sqlite-datasource 3.4.0)

**Comment by fr-ser** [comment]
It is normal that this command fails.

Version 3.5.0 is not yet released on the Grafana webpage.

You can install version 3.5.0 but you need to follow the instructions here: https://github.com/fr-ser/grafana-sqlite-datasource/releases/tag/v3.5.0

**Comment by sensej-j** [comment]
ok, thank you for the info.

**Comment by sensej-j** [comment]
Hello Sergei,
Version 3.5.0 is now running for me.
Can you please show some examples of using the query variable with __text and __value?
How should the query be structured? Example: Select RowName1 AS __text, RowName2 AS __value From TableName; 
How can I use __value? Example: ${GA:value}
How can I use __text? Example: ${GA:text}

I always get the error message with this query. -> Select RowName1 AS __text, RowName2 AS __value From TableName;
Error updating options: Received more than one (2) fields: __text,__value

**Comment by sensej-j** [comment]
Hello Sergej,
Version 3.5.0 is now running for me and using the query variables also works.

Thanks
