### ISSUE TITLE
gpx_sqlite-datasource_windows_amd64.exe zombie process after Grafana exits

### ISSUE THREAD

**Issue by igngi** [fr-ser/grafana-sqlite-datasource#140]
**Describe the bug**
After Grafana exits, gpx_sqlite-datasource_windows_amd64.exe keeps on running.
Running Grafana multiple times will leave multiple instances of datasource_windows_amd64 running.

**To Reproduce**

1. Start Grafana with the extension installed
2. Open any dashboards that use the extension
3. Kill Grafana
4. Check Task Manager

**Screenshots**
![image](https://github.com/user-attachments/assets/59dd80a6-75bf-4d93-b615-b46e183949b6)

**Versions (please complete the following information):**

- OS: Windows
- Run via docker? No
- Browser Edge
- Grafana Version 11.0
- Plugin Version 3.5.0
- Plugin installed via grafana-cli or manually? Manually

Thanks!

**Comment by fr-ser** [comment]
I tried both on my Mac and Windows PC and I could not reproduce the bug.

Could you provide some more details?

I.e. how do you start and stop grafana?

**Comment by igngi** [comment]
Hi, thanks for the prompt reply.

I was starting Grafana by calling grafana.exe from my program (golang's exec.Command).

Because signalling a process to interrupt is not supported on Windows, I need to kill the process, so it doesn't exit properly and gpx_sqlite-datasource_windows_amd64.exe keeps running.

The problem has nothing to do with Grafana or the sqlite extension, so I will close this.

Thanks anyway!
