### ISSUE TITLE
Provisioning through configuration file

### ISSUE THREAD

**Issue by Pamplemousse** [fr-ser/grafana-sqlite-datasource#141]
It would be great to be able to provision this data source using configuration as code.

Here is the documentation on how to do it for "built-in" data sources: https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources .

It seems to be doable by plugins as well, for example, here is documentation on how to do it for `yesoreyeram-infinity-datasource`: https://grafana.com/docs/plugins/yesoreyeram-infinity-datasource/latest/setup/provisioning/ .

As far I can tell reading the documentation, this doesn't seem to be doable for this plugin...

**Comment by fr-ser** [comment]
Thanks for the links.
I haven't looked into this yet but your linked pages seem like it should be doable.

It might even be already supported and just not documented properly.

I will take a look

**Comment by fr-ser** [comment]
Does this section help?
https://github.com/fr-ser/grafana-sqlite-datasource/blob/main/docs/faq.md#can-i-use-provisioning-with-this-plugin

**Comment by Pamplemousse** [comment]
@fr-ser Yes, awesome! Thank you, and sorry for the late confirmation.
