### ISSUE TITLE
Unable to open database file: Permission denied

### ISSUE THREAD

**Issue by icheered** [fr-ser/grafana-sqlite-datasource#19]
I installed the plugin in the plugin directory, all permissions in the /var/lib/grafana folder are set to 750.
I added the datasource of type sqlite-datasource with path to "~/project/data/database.db".

When creating a new panel with the newly added datasource the following error is displayed: 
![image](https://user-images.githubusercontent.com/37150873/103094476-e7077480-45fd-11eb-8a0f-86e548984217.png)

The database.db file also has permission 750.

**Comment by HoaX7** [comment]
I'm facing the same issue, can you tell me the fix? thanks
