### ISSUE TITLE
Importing date column (without time) is not possible

### ISSUE THREAD

**Issue by icheered** [fr-ser/grafana-sqlite-datasource#20]
I have an SQLite3 table with 3 columns: 
- index (INTEGER), 
- date (TEXT) (format = "YYYY-MM-DD"), 
- gainloss (REAL)

I want to plot 'gainloss' against 'date' in grafana, but since date does not have a time-stamp it won't play nicely and doesn't want to plot at all. When I also import the 'index' and set both 'index' as 'date' as Time Formatted Columns it will display the gainloss values but the timescale is set to "1970-01-01 01:00:[INDEX VALUE]".

I hope the image makes it clear.

![image](https://user-images.githubusercontent.com/37150873/103097114-7ca70200-4606-11eb-9092-7d36e9feeb35.png)

**Comment by fr-ser** [comment]
The plugin currently supports two formats for time:
1. If the column is numeric (integer of float) it is assumed, that this is a "unix timestamp" -> this is what happens with your index, but you definitely don't wnat
2. If the column is a string it is assumed to be a RF3339 timestamp like: "2006-01-02T15:04:05Z07:00"

What you might want to try is this:
```sql
WITH converted AS (
    Gainloss,  Date || 'T00:00:00Z00:00' AS DATE
) SELECT Date, Gainloss FROM gainlosstotal ORDER BY Date ASC
```

**Comment by icheered** [comment]
If the datetime is formatted with 'T00:00:00Z' it works like a charm!

Final code that works:
```
WITH converted AS (
    SELECT Gainloss,  Date || 'T00:00:00Z' AS datetime FROM gainlosstotal
)
SELECT datetime, Gainloss FROM converted ORDER BY datetime ASC
```

**Comment by fr-ser** [comment]
I am glad this helped. I will adjust the documentation of the plugin to be more explicit of what I support in the `time formatted column` :ok_hand:
