### ISSUE TITLE
SQLite plugin not visible in Grafana plugin website

### ISSUE THREAD

**Issue by waltervl** [fr-ser/grafana-sqlite-datasource#24]
Your plugin is not visible in the Grafana plugin website https://grafana.com/grafana/plugins
So only a manual installation is possible, is that correct?
I had an issue in finding the correct plugin folder on my Ubuntu  system...

**Comment by fr-ser** [comment]
Yeah, as this section in the readme implies the plugin is not released yet
![image](https://user-images.githubusercontent.com/18115758/103792956-2ee9bb00-5044-11eb-8c33-949b71e27995.png)

I submitted my plugin for review at Grafana here in October: https://github.com/grafana/grafana-plugin-repository/pull/755

Finding the right plugin path (and files to download) is indeed one of the most common issues people face, so getting the plugin approved would be a big help, but waiting is the only thing I can do right now :shrug:

**Comment by waltervl** [comment]
Ah, ok that was not clear for me as newbee Grafana user. I thought the CLI install was no released yet.
Anyway, thanks for the work! I promoted your plugin on the application forum (Domoticz.com).

**Comment by fr-ser** [comment]
Thanks for the promotion. I hope it is a help to you guys.

The versions I submitted there are already somewhat outdated (but I will not change my submission until at least something is approved :sweat_smile: ). I don't know how fast the approvals will be for updates (once the initial plugin is released)
So if you want to have the newest version available you will / might have to go back to the manual installation even in the future, though...

**Comment by fr-ser** [comment]
You had some good timing @waltervl. The plugin got released 5 hours ago :tada: 

It is only version 0.2.2 right now, but if this version fits your needs you should now be able to use the grafana-cli for this (I will update the readme soon)

**Comment by waltervl** [comment]
Congratulations! Perhaps it is wise to document also the version difference with grafana-cli and github install. The Domoticz community is mainly raspberry and there are some ARM bug fixes after 0.2.2 I noticed.
