### ISSUE TITLE
path to in-memory (:memory:) database

### ISSUE THREAD

**Issue by urbanze** [fr-ser/grafana-sqlite-datasource#28]
How can I get the absolute path to in-memory (:memory:) database? Sqlite in grafana need absolute path (disk file).

**Comment by fr-ser** [comment]
I don't see how this is supposed to work.
Let's say you have a python application that used an `in memory sqlite`. That means, that the python database is created ephemerally and not on disk. No other program can access this.

**Comment by urbanze** [comment]
> I don't see how this is supposed to work.
> Let's say you have a python application that used an `in memory sqlite`. That means, that the python database is created ephemerally and not on disk. No other program can access this.

Maybe it could get access to db through "in-memory-shared", with that, several processes can access this region in use by the main task. This can be done by this plugin? (with some work to do).

**Comment by fr-ser** [comment]
I have never heard of a regular application that does this. This would be a super low level (as in hardware-specific maybe even) task.
I can 100% guarantee, that I cannot achieve this, but Pull Requests are welcome.

**Comment by urbanze** [comment]
solved with TMPFS! I created DB file inside directory mounted inside RAM (tmpfs) and now, I have path to use in grafana normally!
