### ISSUE TITLE
Is this code working on raspberry pi model B  arm71 ?

### ISSUE THREAD

**Issue by zinker** [fr-ser/grafana-sqlite-datasource#30]
I am running Grafana 7.4.1 on a raspberry pi 3 B  arm71 en put the plugin 
grafana-sqlite-datasource  in the folder plugins but after restarting  grafana in the  pluginlist nothing shows up.

Do I something wrong ? or is this not working on my type  raspberry  ?

**Comment by fr-ser** [comment]
I don't have that exact device to test against, but I believe the plugin should be compatible.
Can you also try installing the plugin with the grafana-cli? `grafana-cli plugins install frser-sqlite-datasource`

Other than that the (error) logs of Grafana might provide further input :shrug:

**Comment by zinker** [comment]
When I installed I did it with      grafana-cli plugins install frser-sqlite-datasource  , and all files are in the plugins directory.
I tried another plugin and alsothisone show up.
For this reason I remove grafana  completely and install grafana and sqlite  again.
Now everything is working.

the error logs showed no errors.
