### ISSUE TITLE
Variable query not returning any values

### ISSUE THREAD

**Issue by grifmang** [fr-ser/grafana-sqlite-datasource#42]
I'm trying to create a variable from a query to my SQLite database and I can't figure out why it doesn't return anything.

My query is simple,, and it works if used as a graph. Any ideas?

<img width="542" alt="variables" src="https://user-images.githubusercontent.com/7358471/117061618-6b76ac00-acf0-11eb-948a-b2d1fc35d273.png">

**Comment by fr-ser** [comment]
There was a bugfix for something like this here: https://github.com/fr-ser/grafana-sqlite-datasource/blob/master/CHANGELOG.md#102

Can you please fill out the issue template, which includes the Grafana Version and SQLite plugin version?

**Comment by grifmang** [comment]
Sorry about that.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to Dashboard Settings -> Variables -> Choose Query -> Enter 'SELECT * from "table"'
2. Click anywhere to load values
3. Scroll down to values
4. See error (No error. No values being returned)

**Screenshots**
See OP

**Versions (please complete the following information):**

- OS: Windows Server 2019 Standard
- Run via docker? No
- Browser: MS Edge
- Grafana Version: v7.5.3 (3e3cf4dc60)
- Plugin Version 1.0.1
- Plugin installed via grafana-cli or manually? Manually. Extracted ZIP and placed in plugin folder.

**Additional context**
I'm now noticing that this was fixed in the newest version per your reply. I'll try and update.

**Comment by grifmang** [comment]
Seems to be working as expected now on version 1.2.1

My apologies.
