### ISSUE TITLE
Grafana variable queries do not work(Grafana 8.0.2 +grafana-sqlite-datasource 1.2.1)

### ISSUE THREAD

**Issue by sensej-j** [fr-ser/grafana-sqlite-datasource#46]
Hello Sergei,
i need your help.
Today I have installed new Grafana version 8.0.2 with grafana-sqlite-datasource 1.2.1 and since then the Grafana variable queries do not work.
With Grafana version 7.4.3 + grafana-sqlite-datasource 0.2.7 everything works.
It also does not work with Grafana version 8.0.2 + grafana-sqlite-datasource 0.2.7.

Did you get an idea ahead of it?

Grafana version 7.4.3 + grafana-sqlite-datasource 0.2.7: **everything is okay**
![1](https://user-images.githubusercontent.com/78264478/122075134-1e5f1d00-cdfa-11eb-8d4a-5a81a832d8de.jpg)

Grafana version 8.0.2 + grafana-sqlite-datasource 1.2.0: **does not function**
![2](https://user-images.githubusercontent.com/78264478/122076328-1358bc80-cdfb-11eb-87e3-fccb2e236784.jpg)

![3](https://user-images.githubusercontent.com/78264478/122075224-3040c000-cdfa-11eb-9832-51365b65fe8c.jpg)

**Comment by fr-ser** [comment]
Grafana 8 is simply not supported yet.
I'll try to get a version out that supports Grafana v8 and earlier versions to but until then the only reliable way to use the plugin is with Grafana >=7.3.3 & <8.0.0

**Comment by sensej-j** [comment]
Hello Sergej,
thank you for the information.

**Comment by hellebauer** [comment]
> Grafana 8 is simply not supported yet.

Ok, above statement was in relation to grafana-sqlite-datasource 1.2.0.

What about grafana-sqlite-datasource 2.0.0  ?  Does it support Grafana 8 ?

**Comment by fr-ser** [comment]
v2.0.0 of the plugin was also still developed without v8 of Grafana in mind.
I improved the tests a bit yesterday and with that, I should be able to support different versions of Grafana more easily.

I'll try to get a new version of the plugin out with support for Grafana v8 soonish but as of right now there is no plugin version, which I tested against v8 and therefore I cannot say anything about compatibility 🤷🏻

**Comment by hellebauer** [comment]
Thanks..... and no problem....and no rush
Will roll Grafana back to V7 and try again.

Would be good to add some hints here that Grafana8 is not supported

**Comment by radoeka** [comment]
More people encounter the issue: [discussed at grafana forum](https://community.grafana.com/t/query-variable-error/49952/5).
Looking forward to a plugin version that supports Grafana v8.

**Comment by fr-ser** [comment]
Can you try this release: https://github.com/fr-ser/grafana-sqlite-datasource/releases/tag/v2.0.2

It should be fixed but it takes a while for the plugin to be available on the grafana page

You can try this installation: https://github.com/fr-ser/grafana-sqlite-datasource#installing-the-newest-plugin-version-on-an-existing-grafana-with-the-cli

**Comment by radoeka** [comment]
Seems to be working now.
Thanks for the fix!
