### ISSUE TITLE
Milliseconds Support

### ISSUE THREAD

**Issue by UZ9** [fr-ser/grafana-sqlite-datasource#47]
Hi Sergej,

I've recently been using your SQLite data source plugin for Grafana and was wondering if the time formatted columns by any chance supported milliseconds. I have a bunch of data with less than second intervals, and unfortunately, Unix epoch (which worked out of the box, thank you!) doesn't support sub-second timestamps. If there happens to be another time format for this plugin capable of handling milliseconds I would be more than happy to know. Thank you!

**Comment by UZ9** [comment]
After quite a bit of fiddling and wondering why the RFC3339 times weren't being parsed correctly, I finally found the issue: I had the time column set to type ``timestamp``, making the valueType check for ``STRING`` fail. Changing the column to instead be of type ``TEXT`` fixed this issue completely. Cheers!

**Comment by fr-ser** [comment]
Interesting. I will check that out later

**Comment by fr-ser** [comment]
Could you give me an example dataset? Database or CTE?

I am unsure right now if the issue was within the SQLite database or the plugin

**Comment by vsviridov** [comment]
I ended up writing two columns to my database, one in milliseconds, since that's what grafana uses to populate `__from` and `__to` for picking the date range, and another one in RFC3339 format, for using as the time column, to obtain correct millisecond level sorting.

**Comment by fr-ser** [comment]
> since that's what grafana uses to populate __from and __to for picking the date range

You can just divide that number by 1000. I don't understand why you had to create a new column because of that

**Comment by vsviridov** [comment]
Because the column in RFC3339 format cannot be divided by a thousand. This format allows for your plugin to parse with milliseconds. If I store the time in milliseconds grafana interprets it as if it's in year 2745 or something, and if I divide it by a 1000 to get the correct date - I lose milliseconds and all records end up getting sorted incorrectly.

Grafana seemingly ignores `ORDER BY` and sorts on its own by the time field anyway...

**Comment by vsviridov** [comment]
![image](https://user-images.githubusercontent.com/221684/129839865-c3e6bfdb-4dfb-4c60-b8e1-5566f8f45bd3.png)
Sorted by millisecond time divided by 1000

![image](https://user-images.githubusercontent.com/221684/129839949-38e5897a-6c89-4764-92c3-db1d6503816d.png)
Sorted by RFC3339 time

notice that the `POST /api/dashboard/sync-square-catalog 200` is not in the correct place when the `/ 1000` method is employed.

**Comment by fr-ser** [comment]
Hmm. Even by dividing by 1000, you should not lose precision.
I'll check if there is some integer conversion happening somewhere and maybe I can replace that with a float conversion.

It is nice that you found a workaround but I'll see if I can support this more naturally

**Comment by haydnady** [comment]
Hello, 
I tried version 2.1.1 and 2.2.0 but still losing milliseconds, same issue as vsviridov

**Comment by fr-ser** [comment]
> Hello, I tried version 2.1.1 and 2.2.0 but still losing milliseconds, same issue as vsviridov

Can you please expand on the issue and provide me a reproducible example? It looks to work fine on my end 🤷🏻 
![image](https://user-images.githubusercontent.com/18115758/142642967-4d8ff618-9c0e-4e18-b34a-54f9adb2c318.png)

**Comment by haydnady** [comment]
Hello, thanks for looking into this.
Attached two images both are missing milliseconds, one when timestamp is not divided by 1000 the date time is completely off.

![Screenshot 2021-11-22 at 16-16-28 Explore - SQLite- Grafana](https://user-images.githubusercontent.com/31514694/142938186-ce73f0cb-b615-4486-8c35-b02a3a9153a4.png)


![Screenshot 2021-11-22 at 16-17-26 Explore - SQLite- Grafana](https://user-images.githubusercontent.com/31514694/142938203-63877f3f-c336-4c6a-a5bf-acb553ab5220.png)

**Comment by fr-ser** [comment]
> Attached three images, top and middle are missing milliseconds

Can you show me how another plugin shows milliseconds? Currently, I think the milliseconds are processed correctly and Grafana simply removes them when converting the time to a string for the UI...

> the middle image also shows when timestamp is not divided by 1000 the date time is completely off.

Unix timestamps are defined in seconds. You need to divide them by 1000 since Grafana provides them as milliseconds

**Comment by haydnady** [comment]
I got the milliseconds to show by multiplying my 13 digit Unix timestamp by 0.001 and zooming in the plot. If you zoom out then the milliseconds don't show. 

Left side of image shows when zoomed out milliseconds don't show, and right shows when zoomed in milliseconds shows. Thank you for looking into this! 🙏
<img width="727" alt="GOOOoooOD" src="https://user-images.githubusercontent.com/31514694/146445148-7f147a88-4656-482a-bc47-e7eb116a628c.png">
