### ISSUE TITLE
unable to check sqlite file: permission denied

### ISSUE THREAD

**Issue by HoaX7** [fr-ser/grafana-sqlite-datasource#52]
after choosing the sqlite datastore, it says permission denied when i try to use the absolute path of the .sqlite file

**Comment by fr-ser** [comment]
There is a template for creating bug tickets. Please use that to give me some versions of the software you are using.

Also, the logs of Grafana would be very helpful.

Right now I assume: Your Grafana (user) does not have the permissions to open the SQLite file. Nothing the plugin can do about it 🤷🏻
