### ISSUE TITLE
Feature Request: JSON support

### ISSUE THREAD

**Issue by fr-ser** [fr-ser/grafana-sqlite-datasource#53]
There was a PR that aimed to add JSON support: https://github.com/fr-ser/grafana-sqlite-datasource/pull/25

The additions seem to be pretty straightforward but I need to investigate first what kind of features those are so that I can write a test for them.

What would help me is some example query with a CTE or sample database that shows me what kind of query only works with this extension.

**Comment by fr-ser** [comment]
Should be done with: https://github.com/fr-ser/grafana-sqlite-datasource/commit/3ad662c6afb7ea76f0a27e1bda147fcbb1b3f859

**Comment by vsviridov** [comment]
It seems like it's not been published to the main grafana plugin repository.
![image](https://user-images.githubusercontent.com/221684/129787390-ce76164d-2246-42fa-837b-00477a1e0eed.png)

**Comment by fr-ser** [comment]
That is correct. The request for release is made but the actual release I can not force
https://github.com/grafana/grafana-plugin-repository/pull/1020
