### ISSUE TITLE
Time series plotted as table

### ISSUE THREAD

**Issue by kedorlaomer** [fr-ser/grafana-sqlite-datasource#58]
Trying to plot multiple time series as in https://github.com/fr-ser/grafana-sqlite-datasource/issues/43#issuecomment-848959105, I got only one time series:
![image](https://user-images.githubusercontent.com/1071219/132992144-c8471b2b-038e-4100-bed0-35d8f26c0eae.png)
This used to work in an older version of the plugin and grafana (I didn't track exactly when the regression happened). I'm using grafana 7.5.5 from docker and the latest plugin the automatic installer gives me. I even deleted the container and reinstalled to make sure I really have the latest version.

**Comment by fr-ser** [comment]
I tried just now with Grafana 7.5.5 and the latest plugin from Grafana as well as from this repo. All worked for me.
Could you export your dashboard as JSON so I can take a more detailed look (at the full query and settings)?

**Comment by mphuie** [comment]
I'm running into this issue with Grafana 8.1.5.  I also spun up a 7.5.5 container and getting the same results.

**Comment by fr-ser** [comment]
This issue is closed. Please open a new issue and provide a query (with some sample data) and maybe a screenshot of your problem.
