### ISSUE TITLE
Unable to Graph INTEGER

### ISSUE THREAD

**Issue by lucywinters** [fr-ser/grafana-sqlite-datasource#60]
Hi Sergej,

I seem to be unable to graph data that is stored as an INTEGER in my sqlite DB. I have some values as REAL and they work just fine.

I was hoping you might be able to offer some guidance?

**SQLite Table Structure**
7|P_Grid|REAL|0||0
8|P_Load|REAL|0||0\n
**9|P_PV|INTEGER|0||0**
10|Timestamp|TEXT|0||0

If I use the following Query in Grafana it graphs P_Grid & P_Load (both REAL values)
`WITH converted AS (
SELECT P_Load, P_Grid,Timestamp AS datetime FROM site WHERE Timestamp
)
SELECT datetime, P_Load, P_Grid FROM converted ORDER BY datetime ASC`

When I try to add the P_PV value (which is INTEGER) it nothing shows on the graph for P_PV.
**Grafana Query below**
`WITH converted AS (
SELECT P_Load, P_Grid, P_PV, Timestamp AS datetime FROM site WHERE Timestamp
)
SELECT datetime, P_Load, P_Grid, P_PV FROM converted ORDER BY datetime ASC`

Screenshot below shows P_PV values in table
![Screenshot from 2021-09-20 16-59-24](https://user-images.githubusercontent.com/91006826/133966539-1f29b972-bf1f-42df-a4a0-d44d7e9892d4.png)

Screenshot below shows P_PV as part of query, but not showing on graph
![Screenshot from 2021-09-20 16-58-39](https://user-images.githubusercontent.com/91006826/133966544-c4d8fcfe-18a9-415b-95b7-a200f509b8ae.png)

I'm sure this is a simple issue and user error, but I would be so happy for any assistance.

Kind Regards

Lucy

**Comment by fr-ser** [comment]
What version of the SQLite plugin are you using? And what version of Grafana?

**Comment by lucywinters** [comment]
Grafana v7.0.0
SQLite plugin 0.1.5

**Comment by fr-ser** [comment]
Bot the plugin and Grafana version is not officially supported anymore by me 😆 
Can you at least try with an updated plugin?

**Comment by lucywinters** [comment]
Oh My... I'll give you a big hug!
It's working now..... I truly am extremely sorry for having wasted your time on such a simple issue, which was once again user error. 
I've updated to:
Grafana v8.1.4
SQLite plugin 2.1.0

and it magically works now. 
Thank You So Much

Lucy

**Comment by fr-ser** [comment]
Glad to hear that. Always happy to help!
