### ISSUE TITLE
FreeBSD 13 plugin installation fails

### ISSUE THREAD

**Issue by karthi12346** [fr-ser/grafana-sqlite-datasource#78]
In grafana.log got following error:

lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=frser-sqlite-datasource error="fork/exec /var/db/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_freebsd_amd64: no such file or directory"

How to build plugin for FreeBSD?

**Comment by fr-ser** [comment]
If you want to build it yourself take a look here: https://github.com/fr-ser/grafana-sqlite-datasource/blob/master/DEVELOPMENT.md

But if you mean that I should include a FreeBSD build, I will have to investigate a bit first

**Comment by karthi12346** [comment]
I can build and use unsigned version in FreeBSD13:
