### ISSUE TITLE
Request: macOS M1 (darwin_arm64) build

### ISSUE THREAD

**Issue by rrrus** [fr-ser/grafana-sqlite-datasource#80]
Trying to use this plugin on an M1 mac mini.  Getting this error:

`logger=plugin.manager t=2022-02-04T14:37:01.84-0800 lvl=eror msg="Could not start plugin" pluginId=frser-sqlite-datasource err="fork/exec /opt/homebrew/var/lib/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_darwin_arm64: no such file or directory"`

**Comment by fr-ser** [comment]
The plugin is not built on an ARM CPU for darwin. I am planning to switch to a new provider for the SQLite access in Go and I will see if this will allow me to build for arm CPUs as well 👌🏻
