### ISSUE TITLE
All-filter not producing expected query, query returns 0 results

### ISSUE THREAD

**Issue by redturtlepower** [fr-ser/grafana-sqlite-datasource#82]
**Describe the bug**
Using multi-value filters produces query that is not understood by SQLite and retunrs no results:
Generated filter query is like `column="{value1, value2}"` but shouldn't it be like `column IN ("value1", "value2")`?

**To Reproduce**

1. Use sqlite database from plugin
2. Create a multi-value filter and select "All"

**Versions (please complete the following information):**

- OS: Linux 5.11.0-43-generic 20.04.2 Ubuntu
- Grafana Version: 8.1.2
- Plugin Version: 2.1.0
- Plugin installed via grafana-cli or manually? manually

**Comment by fr-ser** [comment]
Maybe as a reference:

I have the following query running fine:
```sql
with data(time, temperature, city) AS (VALUES
(724125600, 10, 'London'), (724161600, 11, 'London'),
(724161600, 20, 'New York'), (724197600, 21, 'New York'),
(724125600, 25, 'Washington'), (724197600, 26, 'Washington')
) SELECT * from data
WHERE city in (${cities:singlequote})
order by time
```

With this being the query variable
```sql
SELECT * FROM (VALUES ('London'), ('New York'), ('Washington'))
```

**Comment by redturtlepower** [comment]
Thanks for the example. This is no bug, the query was wrong on my side. I was not aware of the `:singlequote` command. Also I had a `=` instead of `=` in my query.
