### ISSUE TITLE
Enable syntax highlighting in the query editor

### ISSUE THREAD

**Issue by chaitan94** [fr-ser/grafana-sqlite-datasource#84]
Firstly, thanks for the great plugin :)

I was wondering if is possible to make the query editor use syntax highlighting for SQL. I am not sure how grafana plugins work in general, but after a brief glance at the code, I think maybe just using the `CodeEditor` component instead of `TextArea` might fix this.

**Comment by chaitan94** [comment]
I am not sure if it is documented. The way I found it is I looked at the code for how the official postgres datasource does syntaxt highlighting. [Here is the code](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/postgres/partials/query.editor.html#L6) for that - it uses the CodeEditor component. Of course this is not the correct example, however, as it is still using the old angular based code of grafana instead of react. But a react version of the component seems to exist too [as can be seen here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Monaco/CodeEditor.tsx).

**Comment by chaitan94** [comment]
I've happened to free right now, so I just tried it - it looks much better now! :smile:

I think resize is not a big deal. I use postgres data source in grafana all the time and I never worried too much about not being able to resize. Syntax highlighting, however, at least to me, is much more important.

![image](https://user-images.githubusercontent.com/3336879/175123575-33d06c17-fe7b-4ae7-bf49-7ec7379804a4.png)

**Comment by fr-ser** [comment]
Makes sense. I think I'll see if I can add an option to choose the old or new query editor to get a better feeling about adoption.

**Comment by rayures** [comment]
This is already implemented right?

I. e I have code highlighting wit latest in grafana

**Comment by fr-ser** [comment]
Yes, the latest release has code highlighting with the option to use the old editor.
