### ISSUE TITLE
unable to open database file: out of memory (14)

### ISSUE THREAD

**Issue by mcmellow** [fr-ser/grafana-sqlite-datasource#85]
Raspberry Pi 3B+ with buster
Grafana v8.5.3  - SQLite Plugin v3.0.1
db Name: home/pi/domoticz/domoticz.db
path:  /home/pi/domoticz

At the db settings screen, when pressing Save & Test  2 messages appear.
1) Upper right corner:   Green block with datasource updated
2) Lower left: Red block with error checking db: unable to open database file: out of memory (14)

No error messages in grafana.log
What can I do?

**Comment by fr-ser** [comment]
How does the memory usage and capacity look like on the raspberry?

**Comment by mcmellow** [comment]
See the picture below. My SD-card has 49.6GB free space
![RPi-Memory](https://user-images.githubusercontent.com/15740537/170259527-8cb7209f-05df-44bd-871c-aba7c3d561d1.png)

**Comment by fr-ser** [comment]
That log is just the startup log of the plugin for an SQLite database. It does not provide any information sadly.

Can you provide the options you pass to the plugin for the configuration again?
Also, can you use the CLI tool sqlite3 to open the database on the raspberry via an SSH session?

The last thing to try would be using [v2.2.1](https://github.com/fr-ser/grafana-sqlite-datasource/releases/tag/v2.2.1) of the plugin.

**Comment by mcmellow** [comment]
@fr-ser 
I am able to read data from the domoticz.db by other apps / plugins. It is just Grafana causing trouble.
Uninstalled the v3.0.1 of the grafana-sqlite-datasource plugin and installed the v2.2.1. 
It is visible in the web gui. Adding the domoticz.db to Grafana reuslts in the error
`
error checking db: unable to open database file: no such file or directory
`

Still not working on my RPI with domoticz.db

**Comment by fr-ser** [comment]
But that is a different error message 🤔

Can you provide the settings for the database in Grafana again?

**Comment by mcmellow** [comment]
Name :  home/pi/domoticz/domoticz.db
Path :  home/pi/domoticz

the grafana systemd configuration with the following content
`
[Service]

PrivateTmp=false
ProtectHome=false
`

**Comment by fr-ser** [comment]
> Name : home/pi/domoticz/domoticz.db
Path : home/pi/domoticz

The `name` of the configuration is just the display name in the Grafana UI.
the `path` of the configuration needs to be the full path to the SQLite **file** not the folder.

Can you try with adjusted settings?

**Comment by mcmellow** [comment]
@fr-ser 
Thanks very much. I did understand the the meaning of those field not quite well. The database is connected now.
Also the udate of the plugin to v3.0.1 went OK and the database is still connect OK.
Problem solved, Issue closed
