### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by stefanbie** [fr-ser/grafana-sqlite-datasource#9]
Hi!
Thanks for you effort with the plugin, however I wasn't able to install the it on Windows with the documented instructions:

C:\Program Files\GrafanaLabs\grafana\bin>grafana-cli plugins install frser-sqlite-datasource:
←[31mError←[0m: ←[31m✗←[0m Failed to find requested plugin, check if the plugin_id is correct: 404 not found error

Also, the https://github.com/fr-ser/grafana-sqlite-datasource/archive/vX.X.X.zip does not seem to exist.

BR Stefan

**Comment by fr-ser** [comment]
The plugin is not yet approved/published as an official plugin. That means the `grafana-cli plugins install` command will not work
Try this link for the current raw files (https://github.com/fr-ser/grafana-sqlite-datasource/archive/v0.1.1.zip)

**Comment by stefanbie** [comment]
Thanks, that worked :)
