### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by springjools** [fr-ser/grafana-sqlite-datasource#92]
'grafana-cli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by fr-ser** [comment]
Hello, the grafana-cli is part of the Grafana installation (or not depending on the installation) but not really part of the plugin.

You can find more information here: https://grafana.com/docs/grafana/latest/cli/

I'll close this issue, though as this does not relate to the SQLite plugin.
