### ISSUE TITLE
Docker: Could not start plugin - Unrecognized remote plugin message

### ISSUE THREAD

**Issue by sensej-j** [fr-ser/grafana-sqlite-datasource#94]
Error Plugin unavailable when trying to save and test data source.

![image](https://user-images.githubusercontent.com/78264478/181785046-a516b764-b7f2-46eb-9cf3-1c517fe052fa.png)

![image](https://user-images.githubusercontent.com/78264478/181785298-e7f29fbf-7b8b-4224-9722-b579ee379380.png)

![image](https://user-images.githubusercontent.com/78264478/181785207-6acbbb9c-150f-467d-a2ff-b6c0c485364b.png)

**Grafana-Docker-Log**

logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-29T14:29:00.794365614Z level=error msg="Plugin unavailable" error="plugin unavailable" remote_addr=192.168.178.51 traceID=00000000000000000000000000000000

logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-29T14:29:00.794732911Z level=error msg="Request Completed" method=GET path=/api/datasources/1/health status=503 remote_addr=192.168.178.51 time_ms=8 duration=8.528612ms size=77 referer=http://192.168.178.3:3001/datasources/edit/dpxzCIzVz traceID=00000000000000000000000000000000

- Run via docker
- Browser: chrome
- Grafana Version: 9.0.5 
- Plugin Version: 3.1.1
- Plugin installed via: grafana-cli plugins install frser-sqlite-datasource or Grafana/Plugins -> Install

**Notice**: In Grafana 8.4.1 the tool works

**Comment by fr-ser** [comment]
> * Grafana Version: 9.0.5
> * Plugin Version: 3.1.1
> * Plugin installed via: grafana-cli plugins install frser-sqlite-datasource or Grafana/Plugins -> Install
> 
> **Notice**: In Grafana 8.4.1 the tool works

While the plugin is not (yet) officially tested against Grafana version 9 I just ran it locally and everything worked for me. Since you see it working against a different Grafana version I would be interested if the two environments (with the different Grafana versions) are differing in some regards.

If that does not solve the issue, could you provide some more logs? A whole log from startup from Grafana on DEBUG level would be best

**Comment by sensej-j** [comment]
ok, i check it again

**Comment by sensej-j** [comment]
I can't find any mistake.
All file rights checked
Grafana container restarted multiple times

maybe this error message will help

**Log**
**2022-08-01T16:58:46.905453147+02:00 logger=plugin.manager t=2022-08-01T14:58:46.904520501Z level=error msg="Could not start plugin" pluginId=frser-sqlite-datasource err="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.",**
2022-08-01T16:58:46.905536719+02:00 logger=plugin.manager t=2022-08-01T14:58:46.904894789Z level=error msg="Could not start plugin" pluginId=frser-sqlite-datasource err="plugin frser-sqlite-datasource is already registered",
2022-08-01T16:58:46.907390398+02:00 logger=secrets t=2022-08-01T14:58:46.906974404Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1,
2022-08-01T16:58:46.929960813+02:00 logger=query_data t=2022-08-01T14:58:46.929297549Z level=info msg="Query Service initialization",

**Comment by sensej-j** [comment]
**Installed the tool(frser-sqlite-datasource) in locally Grafana on my Windows: is working**

**Comment by fr-ser** [comment]
> **2022-08-01T16:58:46.905453147+02:00 logger=plugin.manager t=2022-08-01T14:58:46.904520501Z level=error msg="Could not start plugin" pluginId=frser-sqlite-datasource err="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."**
2022-08-01T16:58:46.905536719+02:00 logger=plugin.manager t=2022-08-01T14:58:46.904894789Z level=error msg="Could not start plugin" pluginId=frser-sqlite-datasource err="plugin frser-sqlite-datasource is already registered"
2022-08-01T16:58:46.907390398+02:00 logger=secrets t=2022-08-01T14:58:46.906974404Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1, 2022-08-01T16:58:46.929960813+02:00 logger=query_data t=2022-08-01T14:58:46.929297549Z level=info msg="Query Service initialization",

That does look like a problem indeed. Could you share the whole debug log from start until you try in the Grafana UI? This could give some more context

> I need the tool in Docker, what else can I check?

The tool should definitely work in Docker. Could you maybe share your docker setup so I can try to reproduce the issue (e.g. Dockerfile, docker-compose.yaml, startup command of the container, etc.)?

**Comment by sensej-j** [comment]
Here are the portainer-settings

![image](https://user-images.githubusercontent.com/78264478/182702860-7944a0b6-1073-4313-b14b-58480a514567.png)

![image](https://user-images.githubusercontent.com/78264478/182703055-12cf632a-2114-4ab0-836b-76736d91e9a5.png)

![image](https://user-images.githubusercontent.com/78264478/182704425-73cf7201-ae8a-4cd7-8730-063563ddf1c7.png)

![image](https://user-images.githubusercontent.com/78264478/182703328-bb99c551-2e2a-4f56-a8ae-7e4b39458f85.png)

**Comment by fr-ser** [comment]
It looks like you are using some UI, sadly. If you can provide me with a `Dockerfile` and/or a `docker-compose.yaml`, that reproduces the issue it would help immensely. Without that and further logs I don't think I have any other clues.

**Comment by sensej-j** [comment]
Hello Sergey,
unfortunately I don't have access to docker on the smart home server. I can only create the containers using Portainer GUI.
Which logs do you mean? I only have the log entries in Grafana Portainer.

**Comment by fr-ser** [comment]
> Hello Sergej, unfortunately I don't have access to docker on the smart home server. I can only create the containers using Portainer GUI. 

That makes recreating the issue a bit more difficult but can't be helped I assume. How do you install the plugin in the container, though? Can you log into the container?

> Which logs do you mean? I only have the log entries in Grafana Portainer.

Those are the logs I mean. But it would help to have the full logs from startup up at the DEBUG level (and above) instead of just the two lines you provided.

**Comment by sensej-j** [comment]
_How do you install the plugin in the container, though? Can you log into the container?_

**Option 1:  Portainer-Console**
![image](https://user-images.githubusercontent.com/78264478/183395933-3eb6ed80-bfbf-4953-98ee-5327b353b8d4.png)

![image](https://user-images.githubusercontent.com/78264478/183395814-0c7abc06-350c-4f52-a072-c469f7e00cd3.png)

![image](https://user-images.githubusercontent.com/78264478/183396472-9bb9652d-82fe-42ea-b9ee-91b5d5bdadb6.png)


**Option 2: Grafana GUI**

 
 _up at the DEBUG level_ 

I only have this option

![image](https://user-images.githubusercontent.com/78264478/183393882-51462e17-5b79-41f7-9ba4-42da3d1ac7e7.png)

**Here is the log file**

[Grafana_9.0.5.log](https://github.com/fr-ser/grafana-sqlite-datasource/files/9280891/Grafana_9.0.5.log)

[Grafana_9.0.5_With_Deinstall_and_Install_SQL-Plugin.log.txt](https://github.com/fr-ser/grafana-sqlite-datasource/files/9280996/Grafana_9.0.5_With_Deinstall_and_Install_SQL-Plugin.log.txt)

**Comment by fr-ser** [comment]
The log files are not actually at debug level I believe. You can check this link for details how to enable debug logging: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#log

Can you also try another version of Grafana (inside the docker environment). I would like to find out if the version of Grafana/the plugin is the problem or if it is because it is running in the docker environment.

**Comment by sensej-j** [comment]
Here are two log files.

Grafana Docker Version 8.4.1: Everything works there

Grafana Docker Version 9.0.5: Error Plugin unavailable

[Grafana_Docker_8.4.1_Level_Debug_OK_13.08.2022.txt](https://github.com/fr-ser/grafana-sqlite-datasource/files/9331624/Grafana_Docker_8.4.1_Level_Debug_OK_13.08.2022.txt)

[Grafana_Docker_9.0.5_Level_Debug_Error_13.08.2022.txt](https://github.com/fr-ser/grafana-sqlite-datasource/files/9331625/Grafana_Docker_9.0.5_Level_Debug_Error_13.08.2022.txt)

**Comment by fr-ser** [comment]
Thank you for the log files! Sadly I don't have any more clues from those.

Can you do the following:

1. Uninstall the plugin from the container (if it is still installed) and install it using the environment variable `GF_INSTALL_PLUGINS=frser-sqlite-datasource 3.1.0` ([see link](https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#install-plugins-in-the-docker-container))

2. Could you give me some more information about your setup, so I can try reproducing it.
- What is the operating system/machine of the host PC (are you running on a windows laptop, raspberry pi, ...)
- You are running something called "portainer". I am not familiar with the tool. Is it running any abstractions? E.g. running the docker container in some virtual machine?

**Comment by sensej-j** [comment]
**Notice**

I have tested up to version 9.1.0.
Everything is fine up to Grafana version 9.0.4
The error occurs from Grafana version 9.0.5 to 9.1.0

**_Uninstall the plugin from the container (if it is still installed) and install it using the environment variable_**

Here are the logs from grafana-installing with 
GF_INSTALL_PLUGINS = frser-sqlite-datasource 3.1.0
GF_LOG_CONSOLE_LEVEL = debug


[Log_Grafana_Install_V9.0.4_Level_Debug_OK_17.08.2022.txt](https://github.com/fr-ser/grafana-sqlite-datasource/files/9358703/Log_Grafana_Install_V9.0.4_Level_Debug_OK_17.08.2022.txt)

[Log_Grafana_Install_V9.0.7_Level_Debug_Error_17.08.2022.txt](https://github.com/fr-ser/grafana-sqlite-datasource/files/9358704/Log_Grafana_Install_V9.0.7_Level_Debug_Error_17.08.2022.txt)

Line: 3733
2022-08-17T11:48:04.596905051+02:00 logger=plugin.manager t=2022-08-17T09:48:04.595991268Z level=error msg="Could not start plugin" pluginId=frser-sqlite-datasource err="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."


**_What is the operating system/machine of the host PC (are you running on a windows laptop, raspberry pi, ...)_**

host op: Debian Stretch (9.13)
host machine cpu: 64 Bit Quad-Core 1 GHz 
host Docker version: 19.03.15
host portainer version: 1.17.1

**_You are running something called "portainer". I am not familiar with the tool. Is it running any abstractions? E.g. running the docker container in some virtual machine?_**

https://hub.docker.com/r/portainer/portainer
https://docs.portainer.io/

**Comment by danieltdt** [comment]
I'm facing the same problem for the official grafana Alpine images... I believe this plugins needs a precompile alpine version to work.

**Comment by fr-ser** [comment]
> I'm facing the same problem for the official grafana Alpine images

That is an interesting observation. I'll try that out and see what might be the issue there.

**Comment by fr-ser** [comment]
> I'm facing the same problem for the official grafana Alpine images... I believe this plugins needs a precompile alpine version to work.

Hello @danieltdt, I couldn't reproduce the issue. Could you share your setup so I can see the problem you are facing?
@sensej-j : On the off chance that is it alpine related could you try this grafana image "grafana/grafana:9.0.5-ubuntu" instead of "grafana/grafana:9.0.5"

**Comment by sensej-j** [comment]
I tried the grafana/grafana:9.1.4-ubuntu version today and everything works as before

**Comment by danieltdt** [comment]
> > I'm facing the same problem for the official grafana Alpine images... I believe this plugins needs a precompile alpine version to work.
> 
> Hello @danieltdt, I couldn't reproduce the issue. Could you share your setup so I can see the problem you are facing?

Don't know exactly how, but now the latest docker alpine version is working for me too 🤷🏼
