### ISSUE TITLE
Encryption support with sqlite-jdbc-crypt

### ISSUE THREAD

**Issue by bradygt** [fr-ser/grafana-sqlite-datasource#95]
I'm using https://github.com/Willena/sqlite-jdbc-crypt to secure connection to the database. Is it possible to support that in this Grafana datasource plugin?

**Comment by fr-ser** [comment]
I am not actually aware how this tool works. If you create/use a database via this sqlite-jdbc-crypt tool, can you open the database with any other program, too?

**Comment by bradygt** [comment]
I have only ever used that library to open it. I would think that you could with the same cipher settings and key but that's not my area of expertise either.

**Comment by fr-ser** [comment]
I don't have the setup to test this Java tool. If you could try out opening a database created with the java tool with the SQLite CLI command, then it could tell me if I can support that or not.

It might be also worth asking in the github repo of that encryption, tool, though how other tools are supposed to work with it (that don't use Java for example)
