### ISSUE TITLE
Chart not displaying results if I use the number 0 but will if I use number 0.0 ... possible bug ?

### ISSUE THREAD

**Issue by questuk** [fr-ser/grafana-sqlite-datasource#97]
**The problem is** I use Grafana for my chart and if the very 1st number of row 1 is a 0   ....   I get no graph.
Although data is there !

![image](https://user-images.githubusercontent.com/1677382/188288025-bdd4c3fa-a4ae-412d-a9b4-bf1f391d1991.png)

If I manually change the database first row number to 0.0 from 0 the graph works perfectly.
![02](https://user-images.githubusercontent.com/1677382/188316667-0459b499-8496-460f-ac7a-8ca4b9d82675.png)

It seems that grafana needs to see the number with a decimal to set up the graph ?

My SQLite JSON database setup

![04](https://user-images.githubusercontent.com/1677382/188334751-ce4f44df-d8e6-49fa-b112-1f2cb412432e.png)

![03](https://user-images.githubusercontent.com/1677382/188334773-688ca21f-f77c-4f56-9f27-033740d1e43d.png)

- OS: [e.g. KUbuntu 21.04]
- Run via docker? [e.g. no]
- Browser [Brave]
- Grafana Version 9.1.1
- Plugin Version 3.1.0
- Plugin installed via grafana online

Thanks

**Comment by questuk** [comment]
If you need any more help. please let me know

Thanks

**Comment by fr-ser** [comment]
What would help most would be a reproducible CTE. If that is not possible, then a sample database and query could also help.

RIght now it is very hard to debug the issue without any data or query.

**Comment by questuk** [comment]
Hi Sergej,

Thanks for getting back to me, let me first state I am very new to using SQLIte with JSON and also Grafana, so I may be doing something wrong ?

I have added my working database and if you can look at the image you will see my comments.
I used DB Browser to setup the Table and to do any editing of the data.

[Grafana & SQLIte JSON & number zero problem.zip](https://github.com/fr-ser/grafana-sqlite-datasource/files/9533418/Grafana.SQLIte.JSON.number.zero.problem.zip)

Thanks Gaz

**Comment by fr-ser** [comment]
When I use your query everything looks fine to me (regardless of the first value). In the screenshot in your first message I also see your time range is different. Are you sure that your issue is not simply one of filtering for the right time frame?

If your issue persists, could you maybe export the dashbaord from Grafana (that would include your visualization settings).

**Comment by questuk** [comment]
Hi,

The time range is different as they were taken at different times, but used to show you an example.

Not sure which one you need, so I exported 'Local' & 'For sharing externally' files.

I agree when you use the data in DB Browser etc and use the query everything is shown correctly.
But when the same data and query are used in Grafana the  0  problem arises.

This is the chart you need to look at on my dashboard, as it is referenced to IP15 in the SQLite database.
![Gas](https://user-images.githubusercontent.com/1677382/189519092-9d8226aa-df49-4d70-9a37-efbc4b7faf83.png)

[Exported from Grafana.zip](https://github.com/fr-ser/grafana-sqlite-datasource/files/9542092/Exported.from.Grafana.zip)



Thanks for your time Sergej

Gaz

**Comment by fr-ser** [comment]
I opened this chart and removed the " >= 0 " from the query. While the chart obviously changes due to this it does not become a flat line. How can I reproduce your issue?

Also for time series visualization ordering by time is crucial and should be done in every query.

**Comment by questuk** [comment]
Hi Sergej,

If I remove the " >= 0 " from the query this is what my graph  looks like when the database has 0.0 as the first row of IP 15.
![27](https://user-images.githubusercontent.com/1677382/189537202-638caaa3-447b-4f3a-b2ac-208f8ef87de1.png)


This is the reason I want to show 0 because at 00:00 ( midnight ) the gas meter is set to 0. 
As seen on the video below

>> Also for time series visualization ordering by time is crucial and should be done in every query.
I think I have done this correctly ?
![29](https://user-images.githubusercontent.com/1677382/189537854-f64d5a7a-4355-46a6-b85a-cce9d9dcb5b8.png)

**Here is a video i made a few weeks ago showing the problem** ...

https://user-images.githubusercontent.com/1677382/189538113-defc599e-76ef-4dd8-acb0-6e08ded5a992.mp4

I appreciate your help so far

Thanks Gaz

**Comment by fr-ser** [comment]
> Also for time series visualization ordering by time is crucial and should be done in every query.
I think I have done this correctly ?

The image you showed **selected** the time but you are missing an "order by time ascending" clause, which is integral for a valid timeseries

**Comment by questuk** [comment]
Hi Sergej,

Would it be possible to change my query for me and post it on here ?
As I am very new to SQLIte and JSOn, if you can do that then I will test it. 

Thanks

Gaz

**Comment by questuk** [comment]
Hi

I finally have had some time to come back to this, as I have been very busy lately.

This is my new query, which seems correct referencing your previous comment.

```
select 	json_extract ( DATA,'$.meter_reading' )  as Meter,
		json_extract ( DATA,'$.iso')  as time
from 	Energy
where 	DEVICE = 'IP15'
ORDER BY time ASC ; 
```

The chart still does not work if the 1st line is a  0  in my database.

Any ideas ?

Thanks

Gaz

**Comment by questuk** [comment]
Hi,

Did you ever find a solution to this ?

Thank you Gaz

**Comment by fr-ser** [comment]
Not really. If you could provide a sample query with the data in a CTE or subquery to reproduce the issue that would be most helpful. But I'll try to take another look eventually.

**Comment by questuk** [comment]
Hi,

I have added a zip file with a video & database & query, hope this explains the problem.

Thanks Gaz

[TEST - zero problem - 31-10-22.zip](https://github.com/fr-ser/grafana-sqlite-datasource/files/9899127/TEST.-.zero.problem.-.31-10-22.zip)

**Comment by fr-ser** [comment]
Can you try to pin the problem down to a simpler query? A CTE looks like this

```sql
with cte(timestamp, sensor_name, value)
as (VALUES ('2022-10-30T01:50:00.000+01:00', 'Inlet Pipe', 1),
           ('2022-10-30T01:59:00.000+01:00', 'Inlet Pipe', 5),
           ('2022-10-30T01:10:00.000+00:00', 'Inlet Pipe', 10),
           ('2022-10-30T01:20:00.000+00:00', 'Barrel Lid', 15))
select unixepoch(timestamp) AS ts, value from cte
order by 1 asc
```

Could you provide me such a query (not in a zip file but just here as text) that causes the issue?
